name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development
jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    env: # environment variable
      TEST: 1234r4r3
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve
          browser: chrome
          # wait-on: 'http://localhost:5000'
          config: pageLoadTimeout=100000,baseUrl=http://localhost:5000
