name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development
jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npx serve -s build
          browser: electron
          wait-on: 'http://localhost:5000'
          config: pageLoadTimeout=100000,baseUrl=http://localhost:5000
        # env: # environment variable
        #   WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN}}
